# Site settings
author: Danny Buckley
title: {code.me}
header-img: img/home-bg.png
email: dannyboy.msn@hotmail.com
copyright_name: Danny Buckley
description: > # this means to ignore newlines until "baseurl:"
  A blog about my personal journey learning code from .new
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  DBuckley0126

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
